services:  
  app:
    image: ghcr.io/pocket-id/pocket-id:v2
    environment:
      APP_URL: ${APP_URL}
      TRUST_PROXY: ${TRUST_PROXY}
      RELYING_PARTY_ID: ${RELYING_PARTY_ID}
      RELYING_PARTY_ORIGIN: ${RELYING_PARTY_ORIGIN}
    x-quad-ops-env-secrets:
      pocket-id-encryption-key: ENCRYPTION_KEY
    networks:
      - caddy_default
    volumes:
      - "pocket-id-data:/app/data"
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s

networks:
  caddy_default:
    external: true

volumes:
  pocket-id-data:

secrets:
  pocket-id-encrpytion-key:
    external: true

