services:
  app:
    image: ghcr.io/trly/caddy:2.11
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      - data:/data
      - config:/config
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    x-podman-env-secrets:
      porkbun-api-key: PORKBUN_API_KEY
      porkbun-api-secret-key: PORKBUN_API_SECRET_KEY
      acme-email: ACME_EMAIL

networks:
  default:
    x-quad-ops-network-args:
      - "--dns=94.237.127.9"
      - "--dns=94.237.40.9"

volumes:
  data:
  config:

secrets:
  porkbun-api-key:
    external: true
  porkbun-api-secret-key:
    external: true
  acme-email:
    external: true
