services:
  app:
    image: ghcr.io/rajnandan1/kener:latest
    env_file:
      - ./.env
    environment:
      ORIGIN: ${ORIGIN}
      PORT: ${PORT}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - database:/app/database
    depends_on:
      redis:
        condition: service_started
    networks:
      - default
      - caddy_default
    restart: unless-stopped
    x-quad-ops-env-secrets:
      kener-secret-key: KENER_SECRET_KEY

  redis:
    image: docker.io/library/redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always

networks:
  default:
  caddy_default:
    external: true

volumes:
  database:
  redis-data:
